version: 2

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(!!\/|sdc )approve'
  reset_on_push:
    enabled: true

groups:
  blacklisters:
    required: 1
    users:
      - AWegnerGitHub  # Andy
      - Aralun  # Kyll
      - ArtOfCode-
      - ByteCommander
      - CalvT
      - DasGeek
      - EliahKagan
      - Fortunate-MAN  # Ashish Ahuja
      - Glorfindel83
      - K-Davis1
      - LunarWatcher # Zoe AKA Princess Luna
      - Machavity
      - Makyen
      - MastSE
      - NobodyNada
      - Spevacus
      - ThatRyanPerson # Ryan M
      - Undo1
      - WELZ-gh
      - angussidney
      - bertiebaggio # Rob Hallam
      - bwDraco
      - cigien
      - codygray
      - double-beep
      - ferrybig
      - honnza  # Jan Dvorak
      - iBug
      - jeffschaller # Jeff Schaller
      - magisch
      - metasmoke
      - paper1111
      - quartata
      - rschrieken
      - spacemonaut # doppelgreener
      - superplane39  # Mithrandir
      - surajrao
      - teward
      - tripleee
    author_approval:
      ignored: true
    reject_value: -1
